[phases.setup]
nixPkgs = ["nodejs_22", "npm"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
cmds = ["echo 'Skipping build phase for backend API'"]

[phases.start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
